org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=1.20.4
yarn_mappings=1.20.4+build.3
loader_version=0.15.7

mod_version = 2023.07.10
maven_group = dev.luminous
archives_base_name = alien

fabric_version=0.96.1+1.20.4
baritone_api_version=1.2

# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=1081
# systemProp.http.proxyUser=
# systemProp.http.proxyPassword=

# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=1081
# systemProp.https.proxyUser=
# systemProp.https.proxyPassword=
